- name: Install packages for dotfiles configuration.
  ansible.builtin.package:
    name: "{{ dotfiles_packages }}"
    state: "{{ dotfiles_packages_state }}"

- name: Clone xiple's dotfiles repository.
  ansible.builtin.git:
    repo: 'https://github.com/xiple/dotfiles'
    dest: ~/dotfiles

- name: Use stow to install dotfiles.
  ansible.builtin.command:
    cmd: stow --adopt .
    chdir: ~/dotfiles

- name: Reset local repo and update.
  ansible.builtin.git:
    repo: 'https://github.com/xiple/dotfiles'
    dest: ~/dotfiles
    version: main
    force: yes