---
- name: Verify
  hosts: molecule
  gather_facts: true
  vars_files: ../../defaults/main.yml
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Fail if git is not installed
      ansible.builtin.fail:
        msg: "git package is not installed"
      when: "'git' not in ansible_facts.packages"

    - name: Fail if stow is not installed
      ansible.builtin.fail:
        msg: "stow package is not installed"
      when: "'stow' not in ansible_facts.packages"

    - name: Get information on 'dotfiles' checked out directory
      ansible.builtin.stat:
        path: "{{ dotfiles_repo_local_destination }}"
      register: dotfiles_dir

    - name: Fail if dotfiles directory is not checked out
      ansible.builtin.fail:
        msg: "{{ dotfiles_repo_local_destination }} directory does not exist"
      when: not dotfiles_dir.stat.exists
