---
- name: Verify
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Fail if git is not installed
      ansible.builtin.fail:
        msg: "git package is not installed"
      when: "'git' not in ansible_facts.packages"

    - name: Fail if stow is not installed
      ansible.builtin.fail:
        msg: "stow package is not installed"
      when: "'stow' not in ansible_facts.packages"
